[default]
SQLALCHEMY_DATABASE_URI = 'postgresql://gustavo:1234@localhost:5432/HSC'
SECRET_KEY = "secreto"
SQLALCHEMY_TRACK_MODIFICATIONS = false
UPLOAD_EXTENSIONS = ['.jpg','.png','.gif','.jpeg','.pdf']
UPLOAD_PATH = 'uploads'


MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 587
MAIL_USE_TLS = true
MAIL_USE_SSL = false
MAIL_USERNAME = "chucrutis64@gmail.com"
MAIL_PASSWORD = "tffn xscl tcsi qjbx"
MAIL_DEFAULT_SENDER = "chucrutis64@gmail.com"
